In [1]:
import pandas as pd

In [2]:
data_1= pd.read_csv('waterpump_1.csv')
data_1.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,50785,0.0,2013-02-04,Dmdd,1996,DMDD,35.290799,-4.059696,Dinamu Secondary School,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,other,other
1,51630,0.0,2013-02-04,Government Of Tanzania,1569,DWE,36.656709,-3.309214,Kimnyak,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
2,17168,0.0,2013-02-01,NaN,1567,NaN,34.767863,-5.004344,Puma Secondary,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,other,other
3,45559,0.0,2013-01-22,Finn Water,267,FINN WATER,38.058046,-9.418672,Kwa Mzee Pange,0,...,unknown,soft,good,dry,dry,shallow well,shallow well,groundwater,other,other
4,49871,500.0,2013-03-27,Bruder,1260,BRUDER,35.006123,-10.950412,Kwa Mzee Turuka,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe

In [3]:
data_2 = pd.read_csv('waterpump_2.csv')
data_2.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

# Lets familiarise with our data sets, by the end we should see to which data set does the target column belong to

In [4]:
target_col = pd.read_csv('target columns.csv')
target_col.head()

      id    status_group
0  69572      functional
1   8776      functional
2  34310      functional
3  67743  non functional
4  19728      functional

In [5]:
target_col.tail(5)

          id status_group
59395  60739   functional
59396  27263   functional
59397  37057   functional
59398  31282   functional
59399  26348   functional

In [6]:

data_2.tail(5)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
59395,60739,10.0,2013-05-03,Germany Republi,1210,CES,37.169807,-3.253847,Area Three Namba 27,0,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59396,27263,4700.0,2011-05-07,Cefa-njombe,1212,Cefa,35.249991,-9.070629,Kwa Yahona Kuvala,0,...,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59397,37057,0.0,2011-04-11,NaN,0,NaN,34.017087,-8.750434,Mashine,0,...,monthly,fluoride,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59398,31282,0.0,2011-03-08,Malec,0,Musa,35.861315,-6.378573,Mshoro,0,...,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
59399,26348,0.0,2011-03-23,World Bank,191,World,38.104048,-6.747464,Kwa Mzee Lugawa,0,...,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump

In [7]:
target_col.shape

(59400, 2)

In [8]:
data_2.shape

(59400, 40)

# There are similarities between both the target column dataset and the data_2 data set by Looking at both the data shape and the ID column.

In [9]:
data_2.describe()

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year
count,59400.000000,59400.000000,59400.000000,59400.000000,5.940000e+04,59400.000000,59400.000000,59400.000000,59400.000000,59400.000000
mean,37115.131768,317.650385,668.297239,34.077427,-5.706033e+00,0.474141,15.297003,5.629747,179.909983,1300.652475
std,21453.128371,2997.574558,693.116350,6.567432,2.946019e+00,12.236230,17.587406,9.633649,471.482176,951.620547
min,0.000000,0.000000,-90.000000,0.000000,-1.164944e+01,0.000000,1.000000,0.000000,0.000000,0.000000
25%,18519.750000,0.000000,0.000000,33.090347,-8.540621e+00,0.000000,5.000000,2.000000,0.000000,0.000000
50%,37061.500000,0.000000,369.000000,34.908743,-5.021597e+00,0.000000,12.000000,3.000000,25.000000,1986.000000
75%,55656.500000,20.000000,1319.250000,37.178387,-3.326156e+00,0.000000,17.000000,5.000000,215.000000,2004.000000
max,74247.000000,350000.000000,2770.000000,40.345193,-2.000000e-08,1776.000000,99.000000,80.000000,30500.000000,2013.000000

In [10]:
data_2.isna()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59395,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59396,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59397,False,False,False,True,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59398,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59399,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
# I'll go on and join both data_2 data set with the target_col data set snce they are a similar data set, judging by the ID column
df = pd.merge(data_2, target_col, on='id')
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,functional
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional

In [12]:
# having joined both data sets successfuly lets now write the data set to a new csv file for storage purposes
df.to_csv('TZwaterpump data', index=False)

In [13]:
#Lets now conduct some pre-processing.
#Lets find whether our data has missing values and handle that first.
df.isnull().sum()

id                           0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
status_group                 0
dtype: int64

""""
Here are quite a number of columns with missing values, since we are procesing data in preparation to modelling.
this is the approach i'll take.
    *All columns that contain data that will not affect the model and contain null values will be dropped
    *The rest will be handled based on a specific basis."""

In [14]:
df['funder'].value_counts()

Government Of Tanzania    9084
Danida                    3114
Hesawa                    2202
Rwssp                     1374
World Bank                1349
                          ...
M And P                      1
Tlc/community                1
Mzee Ngwatu                  1
Bgssws                       1
Ccp                          1
Name: funder, Length: 1897, dtype: int64

In [15]:
df['installer'].value_counts()

DWE                     17402
Government               1825
RWE                      1206
Commu                    1060
DANIDA                   1050
                        ...
villager                    1
TLC/Nyengesa Masanja        1
rc ch                       1
Makanya Sisal Estate        1
TSRC                        1
Name: installer, Length: 2145, dtype: int64

In [16]:
#Scheme_name column has 28166 as null values
import math
print((28166*100)/59400)

47.417508417508415

In [17]:
#Approximately 47% of the scheme_name column is a null value, in our model the scheme_name has no effect to prediction 
#So i'll drop the whole column.
df.drop('scheme_name', axis=1, inplace=True)
df.isnull().sum()

id                          0
amount_tsh                  0
date_recorded               0
funder                   3635
gps_height                  0
installer                3655
longitude                   0
latitude                    0
wpt_name                    0
num_private                 0
basin                       0
subvillage                371
region                      0
region_code                 0
district_code               0
lga                         0
ward                        0
population                  0
public_meeting           3334
recorded_by                 0
scheme_management        3877
permit                   3056
construction_year           0
extraction_type             0
extraction_type_group       0
extraction_type_class       0
management                  0
management_group            0
payment                     0
payment_type                0
water_quality               0
quality_group               0
quantity                    0
quantity_group              0
source                      0
source_type                 0
source_class                0
waterpoint_type             0
waterpoint_type_group       0
status_group                0
dtype: int64

In [18]:
#So next lets deal with the columns with null values
#Lets not drop the whole column for the remaining columns and remove the specific rows with null values.
df.dropna(subset=['funder', 'installer', 'subvillage', 'public_meeting', 
                  'scheme_management','permit',], inplace=True)
#Lets check whether the dataframe is updated
df.isnull().sum()

id                       0
amount_tsh               0
date_recorded            0
funder                   0
gps_height               0
installer                0
longitude                0
latitude                 0
wpt_name                 0
num_private              0
basin                    0
subvillage               0
region                   0
region_code              0
district_code            0
lga                      0
ward                     0
population               0
public_meeting           0
recorded_by              0
scheme_management        0
permit                   0
construction_year        0
extraction_type          0
extraction_type_group    0
extraction_type_class    0
management               0
management_group         0
payment                  0
payment_type             0
water_quality            0
quality_group            0
quantity                 0
quantity_group           0
source                   0
source_type              0
source_class             0
waterpoint_type          0
waterpoint_type_group    0
status_group             0
dtype: int64

In [19]:
#Finally now that we are done with null values, lets check whether our data may have duplicates to avoid repetition.
#So i'll use the id column to guide me since it's the unique number between the different water projects.
duplicates = df['id'].duplicated()
duplicated_rows = df[duplicates]
print(duplicated_rows)

Empty DataFrame
Columns: [id, amount_tsh, date_recorded, funder, gps_height, installer, longitude, latitude, wpt_name, num_private, basin, subvillage, region, region_code, district_code, lga, ward, population, public_meeting, recorded_by, scheme_management, permit, construction_year, extraction_type, extraction_type_group, extraction_type_class, management, management_group, payment, payment_type, water_quality, quality_group, quantity, quantity_group, source, source_type, source_class, waterpoint_type, waterpoint_type_group, status_group]
Index: []

[0 rows x 40 columns]

In [20]:
pd.set_option('display.max_columns', None)  # Show all columns
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,functional
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587,Tajiri,0,Pangani,Moa/Mwereme,Tanga,4,8,Mkinga,Moa,1,True,GeoData Consultants Ltd,VWC,True,2009,submersible,submersible,submersible,vwc,user-group,pay per bucket,per bucket,salty,salty,enough,enough,other,other,unknown,communal standpipe multiple,communal standpipe,functional
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365,Kwa Ngomho,0,Internal,Ishinabulandi,Shinyanga,17,3,Shinyanga Rural,Samuye,0,True,GeoData Consultants Ltd,VWC,True,0,swn 80,swn 80,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,non functional

In [21]:
#Let's drop the unnecessary columns.
columns_to_drop = [ 'date_recorded', 'funder', 'wpt_name', 'subvillage', 'region_code', 'lga', 'public_meeting', 
                   'extraction_type_group', 'extraction_type_class', 'management_group', 'payment_type','quality_group', 
                   'quantity_group', 'source_type', 'waterpoint_type_group']
df.drop(columns=columns_to_drop, axis=1, inplace=True)

Bingo!!!! Empty data frame, that's good news, so we have no repetition within our data.

In [22]:
#Let's check our upto date data
df.shape

(48288, 25)

In [23]:
#Lets get our data split into a train and test group ready for modelling.
from sklearn.model_selection import train_test_split
X = df.drop(['status_group'], axis=1)
y= df[['status_group']]
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42, test_size=0.2)

Now let's build our first model based on the data earlier on prepared.

In [24]:
#import necessary libraries.
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree

The dataset is taking up alot o RAM space, soo let's try handle the dataset size FOR efficiency purposes.

In [25]:
df.columns

Index(['id', 'amount_tsh', 'gps_height', 'installer', 'longitude', 'latitude',
       'num_private', 'basin', 'region', 'district_code', 'ward', 'population',
       'recorded_by', 'scheme_management', 'permit', 'construction_year',
       'extraction_type', 'management', 'payment', 'water_quality', 'quantity',
       'source', 'source_class', 'waterpoint_type', 'status_group'],
      dtype='object')

In [26]:
ward_values = df['ward'].value_counts()
ward_values

Igosi          305
Imalinyi       250
Siha Kati      232
Mdandu         231
Nduruma        204
              ...
Machinjioni      1
Liwale B         1
Bugwema          1
Liwale A         1
Igogo            1
Name: ward, Length: 1862, dtype: int64

In [27]:
# Get unique values and their counts in the 'ward' column
unique_values_counts_df = pd.DataFrame(df['ward'].value_counts()).reset_index()
unique_values_counts_df.columns = ['ward', 'count']
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print(unique_values_counts_df)

                       ward  count
0                     Igosi    305
1                  Imalinyi    250
2                 Siha Kati    232
3                    Mdandu    231
4                   Nduruma    204
5                    Msindo    200
6                   Mishamo    198
7                  Chalinze    196
8              Maji ya Chai    189
9                     Usuka    187
10             Ngarenanyuki    164
11                  Vikindu    162
12                  Mtwango    152
13                   Matola    145
14            Zinga/Ikerege    140
15                  Maramba    139
16             Wanging'ombe    138
17                 Kikatiti    134
18                 Olkokola    133
19                 Magomeni    132
20                 Maposeni    130
21                 Igongolo    129
22                  Mvomero    128
23                 Mlangali    124
24         Masama Magharibi    116
25                   Mamire    115
26                Mahongole    114
27                    Simbo    114
28                  Kagongo    113
29                 Lupalilo    113
30                  Kiranyi    112
31                Chinamili    111
32           Siha Mashariki    109
33                   Mkongo    107
34         Masama Mashariki    107
35                    Yombo    106
36                    Tinde    106
37                   Hedaru    105
38                  Malindi    103
39                     Soga    103
40                 Diongoya    103
41                  Makwale    103
42                   Ihanda    102
43                    Nkoma    102
44                  Kimochi    100
45                  Mahembe    100
46       Kirua Vunjo Kusini     98
47             Mabwerebwere     98
48                  Lembeni     95
49                 Leguruki     95
50                    Kanga     94
51                    Bungu     93
52                  Ruhembe     92
53               Mlangarini     92
54                   Mhunze     91
55                   Kidatu     90
56                   Rusumo     89
57                   Ruanda     89
58                  Kifanya     88
59                 Magagura     87
60                   Kisesa     87
61                   Ipande     87
62                 Murufiti     86
63                Munyegera     86
64                 Chanzuru     86
65               Mbulumbulu     85
66               Ilkiding'a     85
67                  Matendo     85
68                  Kakonko     85
69                     Wino     84
70                  Lupembe     83
71                    Muzye     82
72                  Muhinda     82
73               Ilolangulu     81
74                 Nyimbili     81
75        Kibosho Magharibi     81
76                 Mang'ula     81
77             Keni Mengeni     81
78                     Msia     81
79                   Busole     80
80                   Kidodi     79
81                 Kimnyaki     78
82              Rungwe Mpya     77
83            Machame Uroki     76
84                   Lugoba     76
85                  Nkololo     75
86               Nyakitonto     75
87                  Oltroto     75
88                  Mbuyuni     75
89          Boma la ng'ombe     74
90                 Chakwale     74
91                   Lupila     74
92                   Ruhita     74
93                    Luegu     74
94             Oldonyosambu     73
95                  Ipililo     73
96                 Mwandoya     73
97                   Ulenje     73
98                  Manyoni     72
99                    Msata     72
100                Isandula     72
101                  Mbwewe     72
102                King'ori     72
103                  Samuye     72
104                 Mkalamo     71
105                 Hembeti     70
106              Kihorogota     70
107                Ilembula     70
108                Sakasaka     69
109          Machame Kusini     69
110               Rugongowe     69
111                  Isansa     69
112                Busilili     69
113                  Bumera     68
114                 Kalinzi     68
115       Machame Kaskazini     68
116                Mpitimbi     68
117                   Ikolo     67
118                   Iyula     67
119                  Ukumbi     67
120                  Rusesa     67
121             Kalangalala     66
122                   Kileo     66
123              Nyarubungo     66
124                   Mwagi     66
125           Kibondo Urban     65
126                   Ikuka     65
127                  Uwemba     65
128               Kassambya     64
129                Makuyuni     64
130                   Utete     64
131       Pangani Mashariki     64
132                   Janda     64
133                  Madilu     64
134                  Mpindo     64
135                   Mwaya     63
136                   Itaka     63
137               Makambako     63
138        Biharamulo Urban     63
139                   Qurus     62
140                  Matema     62
141               Ushirombo     62
142                 Lusungo     62
143                   Mseke     62
144                  Salawe     62
145                  Ipinda     62
146                    Kahe     61
147                Mang'oto     61
148                 Nyololo     61
149                Matimira     61
150                 Mwamala     60
151                Namajani     60
152                Bugarama     60
153                Buchambi     60
154                   Mamba     60
155                  Dumila     60
156              Ngerengere     60
157                 Kibimba     60
158                Kirongwe     59
159                  Sukuma     59
160       Machame Mashariki     59
161                 Kisanga     59
162                    Kwai     59
163                  Kibiti     59
164                 Bujashi     59
165                  Kwakoa     59
166                   Shume     59
167                  Kisemu     58
168                  Mshewa     58
169           Lagangabilili     58
170          Siha Kaskazini     58
171                 Masange     58
172                Ushirika     57
173                 Lulindi     57
174                Ndalambo     57
175                  Usanda     57
176                Endabash     57
177            Mwika Kusini     57
178         Bonde la Songwe     56
179                   Image     56
180                 Ntobeye     56
181                  Luduga     56
182            Arusha Chini     56
183                  Kiromo     56
184                  Runazi     56
185                 Mabamba     56
186                Nambinzo     56
187                Busagara     56
188                Nyamuswa     56
189                   Njoro     55
190     Old Moshi Mashariki     55
191              Nyabubinza     55
192                 Marumba     55
193                  Mwazye     55
194                Mgombasi     55
195                 Mawengi     55
196                  Iwindi     55
197                   Iwawa     54
198                 Sungaji     54
199   Kurua Vunjo Mashariki     54
200                  Bitale     54
201                 Kihanga     54
202                   Sanje     54
203                   Mkigo     54
204                  Nsimbo     54
205          Msitu wa Tembo     54
206                 Muganza     53
207                   Irole     53
208                  Magawa     53
209                  Rubeho     53
210                Kitagata     53
211                 Mahanje     53
212           Katumbasongwe     53
213             Shinghatini     53
214                 Somanda     53
215               Somangira     53
216        Utengule Usongwe     53
217                   Nzihi     52
218                Mkuranga     52
219                  Ikondo     52
220                 Olmolog     52
221                  Dareda     52
222                  Lusewa     52
223                  Bugoro     52
224                   Chala     52
225                Kilagano     52
226                 Tambani     52
227               Lusahunga     52
228               Namabengo     52
229                   Ngana     51
230                 Myovizi     51
231                  Lumuma     51
232   Kirua Vunjo Magharibi     51
233                    Saja     51
234               Namanyere     51
235              Kidegembye     51
236             Buterankuzi     51
237                 Igalula     51
238       Marangu Mashariki     51
239                 Songoro     51
240                  Mugoma     50
241                    Pahi     50
242             Nyang'hwale     50
243                  Maboga     50
244                   Didia     50
245                    Kate     50
246                 Mazinde     50
247                   Iniho     50
248                 Luchili     50
249                  Isanga     49
250                   Mlali     49
251                 Bujonde     49
252               Lukulendi     49
253                  Malolo     49
254                  Msanzi     49
255                 Rulenge     49
256                  Magoma     49
257                Mererani     49
258                 Halungu     49
259                   Itaba     49
260                   Matai     48
261             Mbalamaziwa     48
262                  Mtumba     48
263                Gwanumpu     48
264                Shishiyu     48
265                  Mwembe     48
266                Ngorongo     48
267                 Kikunde     48
268                 Wangama     48
269                   Dabil     47
270       Kitirima Kingachi     47
271                  Mlimba     47
272                 Kandaga     47
273            Njombe Urban     47
274                   Mwena     47
275                   Kindi     47
276                    Doma     47
277                 Kalenge     47
278              Ketumbeine     47
279                   Mkoma     47
280            Kitongo Sima     47
281                  Mgambo     47
282                  Kiroka     46
283                  Ifunda     46
284                 Kitanda     46
285               Kirangare     46
286                 Kasamwa     46
287                 Nyigogo     46
288              Songambele     46
289                 Makanya     46
290                 Nshamba     46
291                Oltrumet     46
292               Nkoaranga     46
293                 Katumba     46
294                  Shimbi     46
295             Pemba Mnazi     46
296                Kiruruma     46
297                  Sapiwi     46
298                   Mlowa     45
299                  Nkumba     45
300                  Lumuli     45
301                 Izimbya     45
302                 Kasanda     45
303                   Idodi     45
304                  Mogitu     45
305                   Sunga     45
306             Kyela Urban     45
307                  Kibara     45
308               Nyabusozi     44
309                 Lupanga     44
310                   Mtama     44
311                  Neruma     44
312                   Igale     44
313                 Nduguti     44
314                 Gumbiro     44
315                  Kadoto     44
316                 Nkwenda     44
317                Maligisu     43
318                   Ipepo     43
319                Kitahana     43
320           Masama Kusini     43
321                Munzenze     43
322               Chiugutwa     43
323                  Visiga     43
324                   Ikama     43
325                Mtimbira     43
326                  Dakama     43
327                 Namanga     42
328                    Vuga     42
329                 Kabanga     42
330                 Igowole     42
331                  Mikumi     42
332               Mwamgongo     42
333                 Inyonga     42
334                   Itete     42
335                Isingiro     42
336                  Kulimi     42
337                   Ngudu     42
338                   Moivo     42
339               Nyaishozi     41
340           Kilema Kusini     41
341                  Mzenga     41
342                  Melela     41
343               Dongobesh     41
344              Ubetu Kahe     41
345                 Mwaniko     41
346                Bukiriro     41
347                Katerero     41
348                  Ngonga     41
349                 Lingeka     41
350                 Mavanga     41
351                Lugarawa     41
352                  Igunga     41
353                   Mondo     41
354                 Kibakwe     40
355            Mamba Kusini     40
356                   Miono     40
357                  Katoro     40
358                   Maore     40
359                  Mshewe     40
360               Sokoni II     40
361                 Muhunga     40
362                 Matamba     40
363                  Ilunda     40
364          Malenga Makali     40
365                 Msowero     39
366                  Mbogwe     39
367          Kahe Mashariki     39
368             Mwamapalala     39
369                  Uvinza     39
370                 Mkuyuni     39
371               Nyamilama     39
372                 Hombolo     39
373       Uru Kusini Mawela     39
374                   Mbezi     39
375                Kashishi     39
376                Mwandiga     39
377                    Mtii     39
378                 Nyakato     39
379            Loibor Siret     39
380               Mji Mwema     39
381                  Magugu     39
382                Nyambiti     38
383                Mtapenda     38
384                 Chiwezi     38
385                 Kirando     38
386             Murusagamba     38
387           Mwang'halanga     38
388                 Kigongo     38
389               Nyamnyusi     38
390                  Igamba     38
391               Nyamigogo     38
392                    Suji     38
393                  Komuge     38
394                  Inyala     38
395                  Akheri     38
396                   Mvuha     38
397               Miangalua     38
398                  Kazazi     38
399                Mbangala     38
400                   Kabwe     38
401            Mengwe Manda     38
402                Kharumwa     38
403                Mpunguzi     37
404               Nyakahura     37
405                   Tanga     37
406                  Mtibwa     37
407                 Muhange     37
408                 Kighare     37
409         Masama Rundugai     37
410                  Lalago     37
411                  Ligera     37
412                 Itwangi     37
413                  Magara     37
414           Mahida Holili     37
415                  Mahege     36
416               Missungwi     36
417            Nanjara Reha     36
418                  Shelui     36
419                   Ipala     36
420               USA River     36
421                Nyamhula     36
422                  Daluni     36
423                   Ulaya     36
424                 Iguguno     36
425                Kisiwani     36
426                 Lusanga     36
427                 Kaselya     36
428                Bunyambo     36
429                 Mambali     36
430                  Mzumbe     36
431             Ikunguigazi     36
432                  Rubale     36
433                Usangule     36
434                 Mtowisa     36
435                  Chunyu     36
436                Nkoanrua     36
437                Kumsenga     35
438                    Ruvu     35
439                 Mandawa     35
440                 Mwaseni     35
441          Siha Magharibi     35
442                  Ukwama     35
443                   Mombo     35
444              Ilolo Mpya     35
445                 Budekwa     35
446                Magubike     35
447                  Kabasa     35
448                Kaibanja     35
449               Malampaka     35
450                  Berega     35
451                  Mcharo     35
452              Kirwa Keni     35
453                Mundindi     35
454                  Kanazi     34
455                Bulongwa     34
456             Kisarawe II     34
457                  Mtenga     34
458             Unyamikumbi     34
459                   Luana     34
460                    Badi     34
461                 Butimba     34
462                Maretadu     34
463                   Mnazi     34
464               Kimamba A     34
465                 Ikindwa     34
466                 Kongolo     34
467                   Tumbi     34
468                Muungano     33
469                    Pito     33
470                  Masela     33
471                    Goba     33
472                Misezero     33
473                  Ulanda     33
474                  Segala     33
475                 Kishapu     33
476                 Bangata     33
477                 Ilemela     33
478                   Wotta     33
479             Kilimatinde     33
480               Ukenyenge     33
481                  Mkamba     33
482               Isalavanu     33
483                   Sumve     33
484                  Kasela     33
485                Kihagara     33
486           Bwakila Chini     33
487                 Luponde     33
488                   Kyaka     33
489              Nyamtukuza     33
490                 Mandewa     33
491                   Nanga     33
492                  Lubugo     33
493                Itetemia     32
494       Marangu Magharibi     32
495                 Kiomboi     32
496                  Itinje     32
497                  Mwanga     32
498                 Mbugani     32
499                 Nanjota     32
500                 Lilambo     32
501                  Miguwa     32
502                Chabutwa     32
503               Katunguru     32
504                 Mamboya     32
505                 Lunguza     32
506                Mwankoko     32
507              Hungumalwa     32
508          Okoani Kibosho     32
509                 Endasak     32
510                   Ubiri     32
511                 Mwabuma     32
512                  Idunda     32
513                  Kaisho     32
514                 Mugunzu     32
515                Tungamaa     32
516                  Songwa     32
517           Ushiri Ikuini     32
518                Kidugalo     32
519                 Mamsera     32
520                 Kimagai     32
521                 Kasanga     32
522                   Mkowe     32
523                 Chikuyu     31
524                 Ufukoni     31
525                   Mlowo     31
526               Magulilwa     31
527          Mwakanshashala     31
528               Namalenga     31
529                    Rudi     31
530                   Ipera     31
531                  Kiwere     31
532                   Usule     31
533               Mwadobana     31
534                  Kisese     31
535                  Uyumbu     31
536                Mwantini     31
537           Kahamanhalaga     31
538             Makongorosi     30
539                  Mfumbi     30
540                  Rwinga     30
541                Measkron     30
542                   Bunda     30
543                  Magole     30
544                Chiponda     30
545              Magu Urban     30
546                Nanyumbu     30
547                  Nangwa     30
548                Kiloleli     30
549                 Mbokomu     30
550                 Sikonge     30
551                  Haidom     30
552             Uru Shimbwe     30
553                Rungemba     30
554                  Rangwi     30
555           Mwakilyambiti     30
556            Keni  Alleni     30
557                   Iwiji     30
558                  Kibaha     29
559                   Misha     29
560                   Manda     29
561                    Sanu     29
562               Mahuninga     29
563                 Bwawani     29
564                 Mbaramo     29
565                Masumbwe     29
566                Kashasha     29
567                  Mabira     29
568                 Usagara     29
569                  Mnyuzi     29

In [28]:
# Get the number of rows for each unique value in the 'ward' column
rows_per_value = df['ward'].value_counts()

# Calculate the median number of rows
median_rows = rows_per_value.median()

print(f"Median number of rows: {median_rows}")

Median number of rows: 18.0

In [29]:
import numpy as np

# Set a seed for reproducibility
np.random.seed(42)

# Get the number of rows for each unique value in the 'ward' column
rows_per_value = df['ward'].value_counts()

# Calculate the median number of rows
median_rows = rows_per_value.median()

# Round the median value to the nearest whole number just incase it's a float.
rounded_median_rows = int(round(median_rows))

# Create an empty DataFrame to store the final result
final_df = pd.DataFrame()

# Iterate over unique values in the 'ward' column
for unique_value in df['ward'].unique():
    # Get the rows for the current unique value
    rows_for_value = df[df['ward'] == unique_value]
    
    # Check if there are more rows than the rounded median
    if len(rows_for_value) > rounded_median_rows:
        # Randomly choose rows to drop
        rows_to_drop = rows_for_value.sample(n=len(rows_for_value) - rounded_median_rows)
        
        # Drop the randomly chosen rows
        rows_for_value = rows_for_value.drop(rows_to_drop.index)
    
    # Append the rows to the final DataFrame
    final_df = pd.concat([final_df, rows_for_value])

print(final_df.head())

          id  amount_tsh  gps_height installer  longitude  latitude  \
1210   20028      6000.0        1335     Roman  34.954032 -9.867335
3138   63009         0.0        1395     Roman  34.935766 -9.859529
4643   10692         0.0        1548     SHIPO  34.948640 -9.791233
9322   39091      6000.0        1419     Roman  34.943269 -9.850287
15889  35863         0.0        1405     Roman  34.934912 -9.861040

       num_private       basin  region  district_code      ward  population  \
1210             0  Lake Nyasa  Iringa              5  Mundindi          80
3138             0  Lake Nyasa  Iringa              5  Mundindi         300
4643             0  Lake Nyasa  Iringa              5  Mundindi         125
9322             0  Lake Nyasa  Iringa              5  Mundindi          50
15889            0  Lake Nyasa  Iringa              5  Mundindi         350

                   recorded_by scheme_management permit  construction_year  \
1210   GeoData Consultants Ltd               VWC  False               1999
3138   GeoData Consultants Ltd               VWC  False               1999
4643   GeoData Consultants Ltd               VWC  False               1998
9322   GeoData Consultants Ltd               VWC  False               1999
15889  GeoData Consultants Ltd               VWC  False               1999

         extraction_type management                payment water_quality  \
1210             gravity        vwc           pay annually          soft
3138             gravity        vwc              never pay          soft
4643   other - play pump        vwc  pay when scheme fails          soft
9322             gravity        vwc           pay annually          soft
15889            gravity        vwc              never pay          soft

      quantity  source source_class     waterpoint_type    status_group
1210    enough  spring  groundwater  communal standpipe      functional
3138    enough  spring  groundwater  communal standpipe      functional
4643       dry   river      surface  communal standpipe  non functional
9322    enough  spring  groundwater  communal standpipe      functional
15889      dry  spring  groundwater  communal standpipe  non functional

In [30]:
final_df.tail()

,id,amount_tsh,gps_height,installer,longitude,latitude,num_private,basin,region,district_code,ward,population,recorded_by,scheme_management,permit,construction_year,extraction_type,management,payment,water_quality,quantity,source,source_class,waterpoint_type,status_group
57901,28296,0.0,0,World Vision,33.459498,-3.990157,0,Internal,Tabora,2,Mwashiku,0,GeoData Consultants Ltd,Other,False,0,other,other,unknown,soft,insufficient,rainwater harvesting,surface,communal standpipe,functional
57946,10935,0.0,-20,DWE,39.293210,-8.618149,0,Ruvuma / Southern Coast,Lindi,13,Miteja,112,GeoData Consultants Ltd,VWC,True,1986,other,unknown,never pay,salty,dry,shallow well,groundwater,other,non functional
58243,61680,500.0,1262,BRUDER,34.996707,-10.942491,0,Lake Nyasa,Ruvuma,3,Mbinga Urban,160,GeoData Consultants Ltd,Water Board,True,2002,gravity,water board,pay monthly,soft,enough,spring,groundwater,communal standpipe,functional
58667,50306,0.0,0,Joseph nkunda,32.937166,-3.751378,0,Internal,Shinyanga,3,Jana,0,GeoData Consultants Ltd,Private operator,True,0,nira/tanira,private operator,unknown,milky,enough,shallow well,groundwater,hand pump,functional
58713,24286,0.0,0,CCEC,32.624764,-3.636860,0,Lake Victoria,Shinyanga,3,Ngaya,0,GeoData Consultants Ltd,VWC,True,0,gravity,vwc,pay per bucket,soft,enough,lake,surface,other,functional

In [31]:
final_df.shape

(25004, 25)

In [32]:
# Check for 0 values
has_zero_values = (df == 0).any().any()

# Check for null values
has_null_values = df.isnull().any().any()

# Print the results
print(f"DataFrame has 0 values: {has_zero_values}")
print(f"DataFrame has null values: {has_null_values}")

DataFrame has 0 values: True
DataFrame has null values: False

In [33]:
# Check for 0 values in each column
columns_with_zeros = (df == 0).any()

# Get the column names with 0 values
columns_with_zeros_names = columns_with_zeros[columns_with_zeros].index.tolist()

# Print the result
print("Columns with 0 values:", columns_with_zeros_names)

Columns with 0 values: ['amount_tsh', 'gps_height', 'longitude', 'num_private', 'district_code', 'population', 'permit', 'construction_year']

In [34]:
#Sooo based on the cell above, some columns make sense to contain 0 as a value but some are there erroneously.
    #amount_tsh: indicates the amount paid and some water pumps seem to be free so 0 shilling paid, 
    #gps_height: indicates the height above sea level and 0 is a possible value, 
    #longitude: is a geographical measurement and 0 is a possible value, 
    #num_private: is an indication of private wells in a given geographical representation in the data set 0 is a possibility, 
    #district_code : is a unique district identifier and 0 can be a value for the same, 
    #population: the count of people in a selected geographical area, 0 is a possible value, 
    #permit : indicates whether the pump has the necessary permits or not 0 indicates no permits, 
    #construction_year: that's self explanatory and 0 cannot be a value, 


#Let's handle the misplaced 0 values in our data set

In [35]:
#Lets drop all rows with 0 as a value in construction year column we cannot accurately fill those.
df = final_df[(final_df['construction_year'] !=0 )]

In [36]:
final_df.shape

(25004, 25)

In [37]:
#confirm whether the 0 have been handled.
df['construction_year'].value_counts()

2008    1159
2009     937
2010     930
2006     702
2007     679
2000     561
2011     541
2003     537
2004     499
2012     498
1982     472
2005     450
1978     442
2002     398
1999     379
1972     377
1998     358
1985     344
1995     336
1974     316
1984     302
1994     300
1980     283
1988     269
1992     269
1996     260
1990     258
1997     241
1975     225
1986     214
1983     209
1993     208
1976     193
2001     180
1989     169
1970     148
1991     141
1987     134
1981     124
1973     113
1979      99
1977      80
2013      62
1971      60
1963      42
1969      39
1967      36
1968      35
1962      19
1960      16
1964      12
1961      11
1965      11
1966       8
Name: construction_year, dtype: int64

In [38]:
df.shape

(15685, 25)

In [39]:
#lets split the data into test and train
from sklearn.model_selection import train_test_split
X = df.drop(['status_group'], axis=1)
y = df[['status_group']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
#fit a regression model

# import the necessary lib
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=42)

In [41]:
df.columns

Index(['id', 'amount_tsh', 'gps_height', 'installer', 'longitude', 'latitude',
       'num_private', 'basin', 'region', 'district_code', 'ward', 'population',
       'recorded_by', 'scheme_management', 'permit', 'construction_year',
       'extraction_type', 'management', 'payment', 'water_quality', 'quantity',
       'source', 'source_class', 'waterpoint_type', 'status_group'],
      dtype='object')

In [42]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(12548, 24)
(3137, 24)
(12548, 1)
(3137, 1)

In [43]:
#encode the dataset for modelling
#our data set is a mix up of numerical and categorical data soo we select the categirical columns for encoding.
#categorical_columns = df.select_dtypes(include=['installer', 'basin', 'region', 'ward', 'recoded_by', 
                                                #'scheme_management', 'extraction_type', 'management',
                                                #'payment', 'water_quality', 'qauntity', 'source',
                                               #'source_class', 'waterpoint_type',]).columns
# One-Hot Encoding for categorical columns with more than two unique values
#X_train_encoded = pd.get_dummies(X_train, columns=categorical_columns)


# Categorical columns selection based on data types
categorical_columns = X_train.select_dtypes(include=['object']).columns

# One-Hot Encoding for categorical columns with more than two unique values
X_train_encoded = pd.get_dummies(X_train, columns=categorical_columns)
X_train_encoded.shape

(12548, 2164)

In [44]:
#create a logistic regression & fit on train data.
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=42)
#train the model
model.fit(X_train_encoded, y_train)

C:\Users\ADMIN\anaconda3\envs\learn-env\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\ADMIN\anaconda3\envs\learn-env\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=42)

In [45]:
# Categorical columns selection based on data types
categorical_columns = X_test.select_dtypes(include=['object']).columns

# One-Hot Encoding for categorical columns with more than two unique values
X_test_encoded = pd.get_dummies(X_test, columns=categorical_columns)

In [46]:
# Add missing columns to X_test_encoded and set their values to 0
missing_columns = set(X_train_encoded.columns) - set(X_test_encoded.columns)
for col in missing_columns:
    X_test_encoded[col] = 0

# Reorder columns to match X_train_encoded
X_test_encoded = X_test_encoded[X_train_encoded.columns]

In [47]:
#Make sure that both the X_test and X_train have the same number of columns.
print(X_train_encoded.shape)
print(X_test_encoded.shape)

(12548, 2164)
(3137, 2164)

In [62]:
#make the predictions
y_prob = model.predict_proba(X_test_encoded)[:,1]
print(y_prob.shape)
print(type(y_prob))
print(y_prob.ndim)

(3137,)
<class 'numpy.ndarray'>
1

In [63]:
# Print the first five elements
print(y_prob[:5])

[0.04659797 0.08780188 0.07002229 0.07710513 0.06820395]

Conducted the first prediction using a s